services:                # Список всех "служб" (контейнеров) в проекте
  db:                    # Техническое имя сервиса внутри Docker
    image: postgres:15   # Какой образ скачать из Docker Hub (готовая ОС с установленным Postgres)
    container_name: pg_db # Имя, которое вы увидите в списке запущенных контейнеров

    environment:         # Переменные окружения (настройки самой программы внутри контейнера)
      POSTGRES_USER: admin        # Логин администратора
      POSTGRES_PASSWORD: hardpassword    # Пароль
      POSTGRES_DB: users_db      # Имя базы, которая создастся при первом запуске

    ports:               # Связь портов: "Ваш_ПК:Внутри_Контейнера"
      - "5432:5432"      # Позволяет подключаться к базе через localhost:5432

    volumes:             # Сохранение данных (проброс  папки с вашего диска в контейнер)
      - postgres_data:/var/lib/postgresql/data # Чтобы данные не удалились вместе с контейнером

volumes:                 # Объявление именованного хранилища
  postgres_data: